---
- hosts: "{{ class }}"
  vars_files:
      - ./vars/common.yml
      - ./vars/vm_details.yml
      - ./vars/templates.yml
  become: true
  roles:
    - common
- hosts: localhost
  tasks:
    - name: Test Connection [expected Fail]
      shell: ansible all -m ping
      register: task_result
      until: task_result.rc != 0
      retries: 30
      delay: 3
      ignore_errors: yes
- hosts: localhost
  tasks:
    - name: Test Connection [expected Success]
      shell: ansible all -m ping
      register: task_result
      until: task_result.rc == 0
      retries: 20
      delay: 3
      ignore_errors: yes
- hosts: "{{ class }}"
  vars_files:
      - ./vars/common.yml
      - ./vars/vm_details.yml
  become: true
  roles:
    - update_remote_hosts