---
- include: startup.yml
- hosts: masters
  become: true
  vars_files:
      - ./vars/common.yml
      - ./vars/vm_details.yml
  tasks:
    - name: Restart Openshift services [Master]
      service: name=atomic-openshift-master state=restarted
      when: openshift == true
- hosts: nodes
  become: true
  vars_files:
      - ./vars/common.yml
      - ./vars/vm_details.yml
  tasks:
    - name: Restart Openshift services [Master]
      service: name=atomic-openshift-master state=restarted
      when: openshift == true

