---
- include: stopped.yml
- hosts: localhost
  tasks:
    - name: Test Connection [expected Fail]
      shell: ansible all -m ping
      register: task_result
      until: task_result.rc != 0
      retries: 30
      delay: 3
      ignore_errors: yes
- include: startup.yml