---
- name: Gathering Information
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region.code }}"
    filters:
      tag:Class : "{{ class }}"
      tag:Owner : "{{ owner }}"
  register: facts

- name: Destroying Specific Instances
  local_action:
    module: ec2
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_ids: "{{ item.id }}"
    region: "{{ region.code }}"
    state: absent
  with_items: "{{ facts.instances }}"