---
- name: Gathering Information
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region.code }}"
    filters:
      instance-state-name: running
      tag:Class : "{{ class }}"
      tag:Owner : "{{ owner }}"
  register: running

- name: Stopping VMs
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_ids: "{{ item.id }}"
    region: "{{ region.code }}"
    state: stopped
  with_items: "{{ running.instances }}"